# [START app_yaml]
runtime: nodejs10
env_variables:
  MONGO_CONNECTION_STRING: "mongodb://vocchiogrosso:Spring%402019@sortingsite-shard-00-00-r7dez.mongodb.net:27017,sortingsite-shard-00-01-r7dez.mongodb.net:27017,sortingsite-shard-00-02-r7dez.mongodb.net:27017/jobs?ssl=true&replicaSet=SortingSite-shard-0&authSource=admin&retryWrites=true"